<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MailPdfApp</AssemblyName>
    <RootNamespace>MailPdfApp</RootNamespace>
    <AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="PdfSharp" Version="6.1.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="MailPdfApp.Tests\**" />
    <EmbeddedResource Remove="MailPdfApp.Tests\**" />
    <None Remove="MailPdfApp.Tests\**" />
  </ItemGroup>

</Project>